name: Copy to Documentation Repo
on: [push]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Copycat
      uses: ./.github/actions/copycat-action
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        dst_owner: newaetech
        dst_repo_name: documentation-master